// Prayer routes: ordered itineraries across the globe.
//
// stop fields:
//   n     – node id (the same node may appear several times — each is an "occurrence")
//   sec   – section heading that starts at this stop (e.g. a service or time of day)
//   note  – what happens at this point
//   cond  – 'conditional' | 'custom' | 'optional' — overrides the node's own status here
//   only  – nusachim in which this stop exists (otherwise shown as "not in this nusach")
//   t     – per-nusach text for THIS occurrence (overrides the node's default text)
import { R } from './catalog.mjs';
import { KADDISH, KS } from './kaddish.mjs';

const YK_TEXT = {
  arvitAmidah: { em: R('ykEm', 'Arvit/Amidah'), ash: R('ykAsh', 'Maariv Service for Yom Kippur Eve/Amidah'), sef: R('ykSef', 'Maariv Service for Yom Kippur Eve/Amidah') },
  shacharitAmidah: { em: R('ykEm', 'Shacharit/Amidah'), ash: R('ykAsh', 'The Morning Prayers/Amidah'), sef: R('ykSef', 'The Morning Prayers/Amidah') },
  musafAmidah: { em: R('ykEm', 'Mussaf/Amidah'), ash: R('ykAsh', 'Musaf for Yom Kippur/Shemoneh Esrei'), sef: R('ykSef', 'Musaf Service/Amidah') },
  minchaAmidah: { em: R('ykEm', 'Mincha/Amidah'), ash: R('ykAsh', 'Mincha/Amidah for Mincha'), sef: R('ykSef', 'Mincha Service/Amidah') },
};

export const ROUTES = [
  // ───────────────────────── ימים נוראים ─────────────────────────
  {
    id: 'yom-kippur', group: 'ימים נוראים', title: 'יום כיפור', featured: true,
    d: 'יממה אחת של צום, תפילה ותשובה — מן הכפרות והסעודה המפסקת, דרך כל נדרי וחמש תפילות, ועד קול השופר בסוף הנעילה. שימו לב לתחנות החוזרות: העמידה והווידוי חוזרים בכל אחת מחמש התפילות.',
    stops: [
      { n: 'kapparot', sec: 'ערב יום הכיפורים', cond: 'custom', note: 'מנהג ולא חובה; יש פוסקים שהסתייגו ממנו, ויש הנוהגים בו בכסף לצדקה.' },
      { n: 'mincha-erev-yk', note: 'מנחה מוקדמת, ובסופה וידוי ראשון.' },
      { n: 'vidui-yk', note: 'הווידוי הראשון — עוד לפני הסעודה.', t: { em: R('ykEm', 'Mincha for Yom Kippur Eve/Amidah', { start: 'אשמנו', count: 8 }) } },
      { n: 'malkot', cond: 'custom', only: ['em', 'kabbalah', 'ash', 'sef'], note: 'מנהג מלקות סמליות לאחר מנחה.' },
      { n: 'seuda-mafseket', note: 'הסעודה האחרונה לפני הצום.' },
      { n: 'birkat-habanim', cond: 'custom', note: 'ההורים מברכים את הילדים לפני היציאה לבית הכנסת.', t: { em: R('ykEm', 'Blessing the Children'), ash: R('ykAsh', 'Blessing the Children'), sef: R('ykSef', 'Blessing the Children') } },
      { n: 'nerot-yk', note: 'הדלקת הנר וקבלת היום.' },
      { n: 'tefila-zaka', sec: 'ליל יום הכיפורים', cond: 'custom', note: 'מחילה לכל אדם לפני תחילת היום.' },
      { n: 'lecha-eli', cond: 'custom', only: ['em', 'kabbalah'], note: 'פיוט הפתיחה של עדות המזרח.' },
      { n: 'kol-nidrei', note: 'שלוש פעמים, בטלית ובפני ספרי התורה.' },
      { n: 'arvit-yk', note: '״ברוך שם כבוד מלכותו״ בקול רם.' },
      { n: 'kaddish', note: 'חצי קדיש — לפני העמידה הראשונה.', t: KADDISH.ykArvitHalf },
      { n: 'amidah-yk', note: 'עמידה ראשונה מתוך חמש.', t: YK_TEXT.arvitAmidah },
      { n: 'vidui-yk', note: 'וידוי בסוף העמידה בלחש.', t: { em: R('ykEm', 'Arvit/Amidah', { start: 'על סדר א״ב|על חטא', count: 3 }) } },
      { n: 'selichot-yk', note: 'סליחות וי״ג מידות בציבור.' },
      { n: 'vidui-yk', note: 'וידוי בציבור, בסוף הסליחות.' },
      { n: 'avinu-malkenu', note: 'אבינו מלכנו בפתיחת הארון.', t: { ash: R('ykAsh', 'Maariv Service for Yom Kippur Eve/Avinu Malkenu'), sef: R('ykSef', 'Maariv Service for Yom Kippur Eve/Avinu Malkenu') } },
      { n: 'kaddish', note: 'קדיש תתקבל — חותם את ערבית (בעדות המזרח — בסוף הסליחות).', t: KADDISH.ykArvitTitkabal },
      { n: 'kaddish', note: 'קדיש יתום — אחר המזמורים שבסוף ערבית.', t: KADDISH.ykArvitYatom },
      { n: 'shir-hayichud', cond: 'custom', only: ['ash', 'sef'], note: 'למנהג אשכנז ונוסח ספרד.' },
      { n: 'birchot-hashachar', sec: 'שחרית', note: 'הבוקר נפתח כרגיל — אך בלי נעילת סנדלי עור ובלי רחיצה.', t: { em: R('ykEm', 'Shacharit/Blessings Upon Arising'), sef: R('ykSef', 'The Morning Prayers/Blessings Upon Arising'), ash: R('ykAsh', 'The Morning Prayers/Morning Blessings') } },
      { n: 'shacharit-yk', note: 'פסוקי דזמרה וקריאת שמע; ״המלך״ בקול.' },
      { n: 'amidah-yk', note: 'עמידה שנייה.', t: YK_TEXT.shacharitAmidah },
      { n: 'chazara-yk', note: 'חזרת הש״ץ — פיוטים, קדושה וסליחות.' },
      { n: 'vidui-yk', note: 'וידוי בתוך החזרה.', t: { em: R('ykEm', "Shacharit/Reader's Repetition", { start: '^אשמנו מכל', count: 5 }) } },
      { n: 'avinu-malkenu', note: 'אחר החזרה.', t: { em: R('ykEm', "Shacharit/Reader's Repetition", { start: 'אבינו מלכנו', count: 3 }) } },
      { n: 'kaddish', note: 'קדיש תתקבל — חותם את שחרית, לפני הוצאת ספר התורה.', t: KADDISH.ykShacharitTitkabal },
      { n: 'kriat-hatorah-yk', note: 'פרשת אחרי מות והפטרת ״הלוא זה צום אבחרהו״.' },
      { n: 'yizkor', cond: 'custom', only: ['ash', 'sef'], note: 'הזכרת נשמות — למנהג אשכנז ונוסח ספרד.' },
      { n: 'hineni', sec: 'מוסף', cond: 'custom', only: ['ash', 'sef'], note: 'תפילת שליח הציבור.' },
      { n: 'kaddish', note: 'חצי קדיש — לפני עמידת מוסף.', t: KADDISH.ykMusafHalf },
      { n: 'unetaneh-tokef', cond: 'custom', note: 'בעדות המזרח — ״יש נוהגים״.', t: { em: R('ykEm', 'Mussaf/Story of Rabbi Amnon of Mainz'), ash: R('ykAsh', "Musaf for Yom Kippur/Reader's Repetition of the Amidah", { start: 'ונתנה\\s+תקף', count: 8 }), sef: R('ykSef', "Musaf Service/Reader's Repetition", { start: 'ונתנה\\s+תקף', count: 8 }) } },
      { n: 'amidah-yk', note: 'עמידה שלישית — מוסף.', t: YK_TEXT.musafAmidah },
      { n: 'avoda', note: 'שיא התפילה: עבודת הכהן הגדול.' },
      { n: 'eleh-ezkera', cond: 'custom', only: ['ash'], note: 'עשרת הרוגי מלכות.' },
      { n: 'birkat-kohanim', note: 'נשיאת כפיים במוסף.', t: { em: R('ykEm', "Mussaf/Reader's Repetition", { start: 'וכשעומדים הכהנים', count: 2 }), sef: R('ykSef', 'Musaf Service/Priestly Blessing') } },
      { n: 'vidui-yk', note: 'וידוי ברביעית.', t: { em: R('ykEm', 'Mussaf/Amidah', { start: 'על סדר א״ב|על חטא', count: 3 }) } },
      { n: 'kaddish', note: 'קדיש תתקבל — חותם את מוסף.', t: KADDISH.ykMusafTitkabal },
      { n: 'mincha-yk', sec: 'מנחה', note: 'פרשת העריות וספר יונה.' },
      { n: 'kaddish', note: 'חצי קדיש — אחר ההפטרה, לפני העמידה.', t: KADDISH.ykMinchaHalf },
      { n: 'amidah-yk', note: 'עמידה רביעית.', t: YK_TEXT.minchaAmidah },
      { n: 'vidui-yk', note: 'וידוי בחמישית.', t: { em: R('ykEm', 'Mincha/Amidah', { start: 'על סדר א״ב|על חטא', count: 3 }) } },
      { n: 'kaddish', note: 'קדיש תתקבל — חותם את מנחה.', t: KADDISH.ykMinchaTitkabal },
      { n: 'el-nora-alila', sec: 'נעילה', cond: 'custom', only: ['em', 'kabbalah'], note: '״המצא לנו מחילה בשעת הנעילה״.' },
      { n: 'kaddish', note: 'חצי קדיש — אחר ״אשרי״ ו״ובא לציון״, לפני העמידה האחרונה.', t: KADDISH.ykNeilahHalf },
      { n: 'amidah-yk', note: 'עמידה חמישית ואחרונה — ״חתמנו״ במקום ״כתבנו״.', t: { em: R('ykEm', 'Neilah/Amidah'), ash: R('ykAsh', 'Neilah; Concluding Service/Amidah for Neilah'), sef: R('ykSef', 'Neilah Service/Amidah') } },
      { n: 'neila', note: 'חזרת הש״ץ של נעילה, בארון פתוח.' },
      { n: 'vidui-yk', note: 'וידוי אחרון — ״אשמנו״ בלבד.', t: { em: R('ykEm', "Neilah/Reader's Repetition", { start: '^אשמנו', count: 3 }) } },
      { n: 'selichot-yk', note: 'י״ג מידות בפעם האחרונה.', t: { em: R('ykEm', 'Neilah/Slichot', { to: 18 }) } },
      { n: 'avinu-malkenu', note: 'גם בשבת, לרוב המנהגים.', t: { ash: R('ykAsh', 'Neilah; Concluding Service/Avinu Malkenu'), sef: R('ykSef', 'Neilah Service/Avinu Malkenu') } },
      { n: 'neila-closing', note: 'שמע ישראל, ״ברוך שם״ ×3, ״ה׳ הוא האלוהים״ ×7.' },
      { n: 'kaddish', note: 'קדיש תתקבל — האחרון של היום. בעדות המזרח תוקעים בשופר באמצעו, לפני ״תתקבל״; באשכנז — אחריו.', t: KADDISH.ykNeilahTitkabal },
      { n: 'motzaei-yk', sec: 'מוצאי החג', note: 'ערבית, הבדלה — וקידוש לבנה.' },
      { n: 'kiddush-levana', cond: 'custom', note: 'נהוג לקדש את הלבנה בצאת יום הכיפורים.' },
    ],
  },
  {
    id: 'rosh-hashana', group: 'ימים נוראים', title: 'ראש השנה',
    d: 'יום הדין ויום ההכתרה: מן הסליחות והתרת הנדרים, דרך סדר הסימנים, ועד קולות השופר, מוסף של מלכויות־זכרונות־שופרות ותשליך.',
    stops: [
      { n: 'selichot', sec: 'ערב ראש השנה', note: 'סליחות באשמורת הבוקר.' },
      { n: 'hatarat-nedarim', cond: 'custom', note: 'בפני שלושה.' },
      { n: 'arvit-rh', sec: 'ליל ראש השנה', note: 'עמידה של ראש השנה.' },
      { n: 'kiddush-rh', note: 'קידוש ו״שהחיינו״.' },
      { n: 'simanim', cond: 'custom', note: '״יהי רצון״ על כל סימן.' },
      { n: 'birkat-hamazon', note: 'עם ״יעלה ויבוא״ ו״הרחמן הוא יחדש עלינו את השנה״.' },
      { n: 'amidah-rh', sec: 'שחרית', note: 'עמידה וחזרה עם פיוטים.' },
      { n: 'avinu-malkenu', note: 'לא בשבת (לרוב המנהגים).' },
      { n: 'kaddish', note: 'קדיש תתקבל — חותם את שחרית.', t: KADDISH.rhShacharit },
      { n: 'kriat-hatorah', note: 'יום א׳: ״וה׳ פקד את שרה״; יום ב׳: העקדה.', t: { em: [R('rhEm', 'Reading of the Torah for the First Day'), R('rhEm', 'Haftarah for the First Day of Rosh Hashana')], ash: R('rhAsh', 'Reading of the Torah'), sef: R('rhSef', 'Reading of the Torah') } },
      { n: 'kaddish', note: 'חצי קדיש — אחר קריאת המפטיר, לפני ההפטרה.', t: KADDISH.rhMaftir },
      { n: 'shofar', note: 'תקיעות דמיושב.' },
      { n: 'kaddish', sec: 'מוסף', note: 'חצי קדיש — לפני עמידת מוסף.', t: KADDISH.rhMusafHalf },
      { n: 'unetaneh-tokef', cond: 'custom', note: 'בעדות המזרח — ״יש נוהגים״.' },
      { n: 'musaf-rh', note: 'מלכויות, זכרונות, שופרות — עם תקיעות דמעומד.' },
      { n: 'aleinu', note: 'כאן מקומו המקורי — פתיחת ״מלכויות״.' },
      { n: 'kaddish', note: 'קדיש תתקבל — חותם את מוסף.', t: KADDISH.rhMusafTitkabal },
      { n: 'tashlich', sec: 'אחר הצהריים', cond: 'custom', note: 'ליד מקור מים.' },
    ],
  },

  // ───────────────────────── מעגל החיים ─────────────────────────
  {
    id: 'wedding', group: 'מעגל החיים', title: 'חתונה ושבע ברכות', featured: true,
    d: 'מן קבלת הפנים והכתובה, אל מתחת לחופה — אירוסין, טבעת, קריאת הכתובה ושבע ברכות — ועד שבירת הכוס, הסעודה ושבעת ימי המשתה. שבע הברכות מופיעות פעמיים: תחת החופה, ושוב אחרי ברכת המזון.',
    stops: [
      { n: 'kabbalat-panim', sec: 'לפני החופה', note: 'חתימת העדים על הכתובה; באשכנז — גם ״באדעקן״.' },
      { n: 'erusin', sec: 'תחת החופה', note: 'ברכת היין וברכת האירוסין, ואז הטבעת: ״הרי את מקודשת לי…״.' },
      { n: 'ketuba-reading', note: 'קריאת הכתובה בקול — מפרידה בין אירוסין לנישואין.' },
      { n: 'sheva-brachot', note: 'שבע הברכות על כוס שנייה.' },
      { n: 'shvirat-hakos', cond: 'custom', note: '״אם אשכחך ירושלים״.' },
      { n: 'yichud', cond: 'custom', only: ['ash', 'sef', 'chabad'], note: 'באשכנז ובקהילות החסידים.' },
      { n: 'netilat-hamotzi', sec: 'סעודת המצווה', note: 'פתיחת הסעודה.' },
      { n: 'zimmun', note: 'זימון מיוחד לחתונה: ״שהשמחה במעונו״.', t: { em: R('em', 'Assorted Blessings and Prayers/Sheva Berachot', { from: 0, count: 2 }) } },
      { n: 'birkat-hamazon', note: 'ברכת המזון על הכוס.' },
      { n: 'sheva-brachot', note: 'שבע ברכות אחרי ברכת המזון — וכך בכל סעודה בשבעת ימי המשתה, בתנאי שיש מניין ו״פנים חדשות״.' },
    ],
  },
  {
    id: 'brit-mila', group: 'מעגל החיים', title: 'ברית מילה',
    d: 'ביום השמיני: הכנסת התינוק בברית אברהם אבינו, קריאת השם וסעודת מצווה.',
    stops: [
      { n: 'tachanun', cond: 'conditional', note: 'בציבור שיש בו בעל ברית אין אומרים תחנון — התחנה מסומנת כדי להראות מה נשמט.', omit: true },
      { n: 'brit-mila', sec: 'הברית', note: '״ברוך הבא״, ותפילות הסנדק ואבי הבן.', t: { em: R('em', 'Assorted Blessings and Prayers/Brit Mila', { to: 22 }) } },
      { n: 'kisse-eliyahu', cond: 'custom', note: '״זה הכיסא של אליהו הנביא״.' },
      { n: 'brit-mila', note: 'ברכת המוהל וברכת האב — ״להכניסו בבריתו של אברהם אבינו״.', t: { em: R('em', 'Assorted Blessings and Prayers/Brit Mila', { from: 28, to: 32 }) } },
      { n: 'brit-mila', note: 'ברכה על הכוס ותפילת קריאת השם.', t: { em: R('em', 'Assorted Blessings and Prayers/Brit Mila', { from: 32 }) } },
      { n: 'netilat-hamotzi', sec: 'סעודת מצווה', note: 'סעודת הברית.' },
      { n: 'birkat-hamazon', note: 'ברכת המזון.' },
      { n: 'harachaman-brit', note: '״הרחמן״ מיוחדים לברית.' },
    ],
  },

  // ───────────────────────── יומיום ─────────────────────────
  {
    id: 'boker', group: 'יומיום', title: 'השכמת הבוקר וברכות השחר',
    d: 'מן הרגע הראשון של היקיצה ועד הכניסה לתפילה.',
    stops: [
      { n: 'modeh-ani', sec: 'עם היקיצה' },
      { n: 'birchot-hashachar', note: 'נטילת ידיים, ״אשר יצר״, ״אלוהי נשמה״ ושאר הברכות.' },
      { n: 'birchot-hatorah' },
      { n: 'tallit', sec: 'הכנה לתפילה' },
      { n: 'tefillin', note: 'בימי חול.' },
      { n: 'petichat-eliyahu', cond: 'custom', only: ['em', 'kabbalah'] },
      { n: 'akeda-korbanot', cond: 'custom' },
      KS.korbanot,
    ],
  },
  {
    id: 'shacharit', group: 'יומיום', title: 'שחרית לחול',
    d: 'תפילת הבוקר של יום חול, מן הפתיחה ועד ״עלינו״. הקדיש מפריד בין חלקי התפילה ומופיע בה כמה פעמים.',
    stops: [
      { n: 'birchot-hashachar', sec: 'הכנה' },
      { n: 'tallit' },
      { n: 'tefillin' },
      { n: 'akeda-korbanot', cond: 'custom' },
      KS.korbanot,
      { n: 'pesukei-dezimra', sec: 'פסוקי דזמרה' },
      KS.pesukei,
      { n: 'shema', sec: 'קריאת שמע ועמידה' },
      { n: 'amidah' },
      { n: 'tachanun', cond: 'conditional' },
      KS.tachanun,
      { n: 'kriat-hatorah', sec: 'קריאת התורה', cond: 'conditional', note: 'בשני ובחמישי.' },
      KS.torah,
      { n: 'ashrei', sec: 'סיום' },
      KS.uvaLetzion,
      { n: 'shir-shel-yom', note: 'באשכנז — אחר ״עלינו״.' },
      KS.shirShelYom,
      { n: 'kaveh', cond: 'custom' },
      KS.kaveh,
      { n: 'aleinu', note: 'בעדות המזרח — חותם את התפילה.' },
      KS.aleinu,
    ],
  },
  {
    id: 'mincha', group: 'יומיום', title: 'מנחה לחול',
    d: 'תפילה קצרה באמצע היום — ״לא נענה אליהו אלא בתפילת המנחה״.',
    stops: [
      { n: 'mincha-opening' },
      KS.minchaHalf,
      { n: 'amidah', t: { em: R('em', 'Weekday Mincha/Amida'), ash: R('ash', 'Weekday/Minchah/Amida'), sef: R('sef', 'Weekday Mincha/Amidah'), chabad: R('chabad', 'Mincha/Amidah') } },
      { n: 'tachanun', cond: 'conditional', t: { em: R('em', 'Weekday Mincha/Vidui'), ash: R('ash', 'Weekday/Minchah/Post Amidah/Tachanun'), sef: R('sef', 'Weekday Mincha/Tachanun'), chabad: R('chabad', 'Mincha/Tachanun') } },
      KS.minchaTitkabal,
      KS.minchaYatomEm,
      { n: 'aleinu', t: { em: R('em', 'Weekday Mincha/Alenu'), ash: R('ash', 'Weekday/Minchah/Concluding Prayers/Alenu'), chabad: R('chabad', 'Mincha/Aleinu') } },
      KS.minchaAleinu,
    ],
  },
  {
    id: 'arvit', group: 'יומיום', title: 'ערבית לחול',
    d: 'תפילת הלילה. במקורה רשות, אך ישראל קיבלוה עליהם כחובה.',
    stops: [
      KS.arvitBarchu,
      { n: 'arvit-shema' },
      KS.arvitHalf,
      { n: 'amidah', note: 'בלי חזרת הש״ץ.', t: { em: R('em', 'Weekday Arvit/Amidah'), ash: R('ash', 'Weekday/Maariv/Amidah'), sef: R('sef', 'Weekday Maariv/Amidah'), chabad: R('chabad', 'Maariv', { start: 'אדני,? שפתי תפתח' }) } },
      KS.arvitTitkabal,
      { n: 'sefirat-haomer', cond: 'conditional', note: 'בין פסח לשבועות.' },
      KS.arvitYatomEm,
      { n: 'aleinu', t: { em: R('em', 'Weekday Arvit/Alenu'), ash: R('ash', 'Weekday/Maariv/Alenu') } },
      KS.arvitAleinu,
      { n: 'kriat-shema-al-hamita', sec: 'לפני השינה' },
    ],
  },
  {
    id: 'yom-chol', group: 'יומיום', title: 'יום חול שלם',
    d: 'שלוש התפילות של יום אחד — עמידה שלוש פעמים, ״עלינו״ שלוש פעמים — מן ״מודה אני״ ועד קריאת שמע שעל המיטה.',
    stops: [
      { n: 'modeh-ani', sec: 'בוקר' },
      { n: 'birchot-hashachar' },
      { n: 'pesukei-dezimra' },
      KS.pesukei,
      { n: 'shema' },
      { n: 'amidah', note: 'עמידה — שחרית.' },
      { n: 'tachanun', cond: 'conditional' },
      KS.tachanun,
      { n: 'ashrei' },
      KS.uvaLetzion,
      { n: 'aleinu', note: 'עלינו — שחרית.' },
      KS.aleinu,
      { n: 'birchot-hanehenin', sec: 'במשך היום' },
      { n: 'birkat-hamazon' },
      { n: 'mincha-opening', sec: 'מנחה' },
      KS.minchaHalf,
      { n: 'amidah', note: 'עמידה — מנחה.', t: { em: R('em', 'Weekday Mincha/Amida'), ash: R('ash', 'Weekday/Minchah/Amida'), sef: R('sef', 'Weekday Mincha/Amidah'), chabad: R('chabad', 'Mincha/Amidah') } },
      KS.minchaTitkabal,
      KS.minchaYatomEm,
      { n: 'aleinu', note: 'עלינו — מנחה.', t: { em: R('em', 'Weekday Mincha/Alenu'), ash: R('ash', 'Weekday/Minchah/Concluding Prayers/Alenu'), chabad: R('chabad', 'Mincha/Aleinu') } },
      KS.minchaAleinu,
      { n: 'arvit-shema', sec: 'ערבית' },
      KS.arvitHalf,
      { n: 'amidah', note: 'עמידה — ערבית.', t: { em: R('em', 'Weekday Arvit/Amidah'), ash: R('ash', 'Weekday/Maariv/Amidah'), sef: R('sef', 'Weekday Maariv/Amidah'), chabad: R('chabad', 'Maariv', { start: 'אדני,? שפתי תפתח' }) } },
      KS.arvitTitkabal,
      KS.arvitYatomEm,
      { n: 'aleinu', note: 'עלינו — ערבית.', t: { em: R('em', 'Weekday Arvit/Alenu'), ash: R('ash', 'Weekday/Maariv/Alenu') } },
      KS.arvitAleinu,
      { n: 'kriat-shema-al-hamita', sec: 'לילה' },
    ],
  },
  {
    id: 'seuda', group: 'יומיום', title: 'סעודה וברכת המזון',
    d: 'סעודה של לחם מתחילתה ועד סופה.',
    stops: [
      { n: 'netilat-hamotzi' },
      { n: 'birchot-hanehenin', cond: 'conditional', note: 'על מאכלים שאינם נפטרים ב״המוציא״.' },
      { n: 'zimmun', cond: 'conditional', note: 'בשלושה ומעלה.' },
      { n: 'birkat-hamazon' },
      { n: 'maein-shalosh', cond: 'conditional', note: 'כשאוכלים מזונות או פירות בלי לחם — במקום ברכת המזון.' },
    ],
  },

  // ───────────────────────── שבת ומועדים ─────────────────────────
  {
    id: 'shabbat', group: 'שבת ומועדים', title: 'שבת',
    d: 'מהדלקת הנרות ועד ההבדלה: שלוש תפילות, שלוש סעודות, וקידוש פעמיים.',
    stops: [
      { n: 'nerot-shabbat', sec: 'ערב שבת' },
      { n: 'shir-hashirim', cond: 'custom' },
      { n: 'yedid-nefesh', cond: 'custom' },
      { n: 'kabbalat-shabbat', sec: 'ליל שבת' },
      { n: 'lecha-dodi' },
      { n: 'kaddish', only: ['ash', 'sef', 'chabad'], note: 'קדיש יתום — אחר ״מזמור שיר ליום השבת״ ו״ה׳ מלך״.', t: KADDISH.kabbalatShabbatAsh },
      { n: 'kaddish', only: ['em', 'kabbalah'], note: 'קדיש דרבנן (״על ישראל״) — בעדות המזרח, אחר ״במה מדליקין״ שבסוף קבלת שבת.', t: KADDISH.kabbalatShabbatEm },
      { n: 'arvit-shabbat', note: 'בתוכה: חצי קדיש לפני העמידה וקדיש תתקבל אחר ״מגן אבות״.' },
      { n: 'shalom-aleichem', sec: 'סעודת ליל שבת', cond: 'custom' },
      { n: 'eshet-chayil', cond: 'custom' },
      { n: 'birkat-habanim', cond: 'custom' },
      { n: 'atkinu', cond: 'custom' },
      { n: 'kiddush-shabbat' },
      { n: 'netilat-hamotzi', note: 'על שתי ככרות — ״לחם משנה״.' },
      { n: 'zemirot', cond: 'custom' },
      { n: 'birkat-hamazon', note: 'עם ״רצה והחליצנו״.' },
      { n: 'shacharit-shabbat', sec: 'בוקר שבת' },
      { n: 'amidah-shabbat' },
      { n: 'kaddish', note: 'קדיש תתקבל — אחר חזרת הש״ץ של שחרית.', t: KADDISH.shabbatShacharit },
      { n: 'kriat-hatorah-shabbat' },
      { n: 'birkat-hachodesh', cond: 'conditional' },
      { n: 'kaddish', note: 'חצי קדיש — לפני עמידת מוסף.', t: KADDISH.shabbatMusafHalf },
      { n: 'musaf-shabbat' },
      { n: 'kaddish', note: 'קדיש תתקבל — אחר מוסף.', t: KADDISH.shabbatMusafTitkabal },
      { n: 'kiddush-yom', sec: 'סעודת היום' },
      { n: 'zemirot', cond: 'custom', t: { em: R('em', 'Daytime Meal/Daytime Meal'), ash: R('ash', 'Shabbat/Daytime Meal/Zemirot for Second Meal'), sef: R('sef', 'Shabbat Day Meal/Zemirot') } },
      { n: 'birkat-hamazon' },
      { n: 'mincha-shabbat', sec: 'אחר הצהריים' },
      { n: 'pirkei-avot', cond: 'custom' },
      { n: 'kaddish', cond: 'custom', note: 'קדיש דרבנן — אחר לימוד פרקי אבות.', t: KADDISH.pirkeiAvot },
      { n: 'seuda-shlishit' },
      { n: 'havdalah', sec: 'מוצאי שבת' },
      { n: 'veyiten-lecha', cond: 'custom' },
    ],
  },
  {
    id: 'rosh-chodesh', group: 'שבת ומועדים', title: 'ראש חודש',
    d: 'חידוש הירח: הכרזה בשבת שלפני, תוספות בעמידה, הלל ומוסף.',
    stops: [
      { n: 'birkat-hachodesh', sec: 'בשבת שלפני' },
      { n: 'amidah', sec: 'שחרית של ראש חודש' },
      { n: 'yaale-veyavo', note: 'נוסף לעמידה.' },
      { n: 'hallel', note: 'חצי הלל.' },
      { n: 'kaddish', note: 'קדיש תתקבל — אחר ההלל.', t: KADDISH.rcHallel },
      { n: 'kriat-hatorah', note: '״וביום השבת… ובראשי חדשיכם״.' },
      { n: 'kaddish', note: 'חצי קדיש — בסיום קריאת התורה, לפני מוסף.', t: KADDISH.rcTorah },
      { n: 'musaf-rosh-chodesh' },
      { n: 'kaddish', note: 'קדיש תתקבל — אחר מוסף.', t: KADDISH.rcMusaf },
      { n: 'barchi-nafshi', cond: 'custom' },
      { n: 'kaddish', cond: 'custom', note: 'קדיש יתום — אחר ״ברכי נפשי״.', t: KADDISH.rcBarchiNafshi },
      { n: 'birkat-hamazon', sec: 'סעודה', note: 'עם ״יעלה ויבוא״.' },
      { n: 'kiddush-levana', sec: 'בימים שאחריו', cond: 'conditional' },
    ],
  },
  {
    id: 'pesach-seder', group: 'שבת ומועדים', title: 'ליל הסדר',
    d: 'ט״ו הסימנים של ליל הסדר — ״קדש ורחץ, כרפס יחץ, מגיד רחצה, מוציא מצה, מרור כורך, שולחן עורך, צפון ברך, הלל נרצה״ — וארבע כוסות.',
    stops: [
      { n: 'bedikat-chametz', sec: 'לפני החג', cond: 'conditional' },
      { n: 'kadesh', sec: 'הסדר', note: 'כוס ראשונה.' },
      { n: 'urchatz' },
      { n: 'karpas' },
      { n: 'yachatz' },
      { n: 'maggid', note: 'כוס שנייה בסופו.' },
      { n: 'ma-nishtana', note: 'בתוך המגיד.' },
      { n: 'rachtza' },
      { n: 'motzi-matza' },
      { n: 'maror' },
      { n: 'korech' },
      { n: 'shulchan-orech' },
      { n: 'tzafun' },
      { n: 'barech', note: 'כוס שלישית.' },
      { n: 'hallel-seder', note: 'כוס רביעית.' },
      { n: 'nirtzah' },
      { n: 'sefirat-haomer', sec: 'הלילה השני', cond: 'conditional', note: 'מליל ט״ז מתחילים לספור.' },
    ],
  },
  {
    id: 'sukkot', group: 'שבת ומועדים', title: 'סוכות',
    d: 'שבעה ימים בסוכה עם ארבעת המינים, ובסופם שמיני עצרת ושמחת תורה.',
    stops: [
      { n: 'sukka', sec: 'ליל החג', note: 'אושפיזין וברכת ״לישב בסוכה״.' },
      { n: 'kiddush-yom-tov' },
      { n: 'amidah-regalim', sec: 'בוקר החג' },
      { n: 'lulav' },
      { n: 'hallel', note: 'הלל שלם.' },
      { n: 'hoshanot' },
      { n: 'musaf-regalim' },
      { n: 'hoshanot', sec: 'הושענא רבה', note: 'שבע הקפות וחביטת ערבות.', t: { ash: R('ash', "Festivals/Sukkot/Hosha'anot/Hosha'ana Rabba"), sef: R('sef', 'Sukkot/Hoshana Rabba') } },
      { n: 'geshem', sec: 'שמיני עצרת' },
      { n: 'yizkor', cond: 'custom', only: ['ash', 'sef'] },
      { n: 'hakafot', sec: 'שמחת תורה', cond: 'custom' },
    ],
  },
  {
    id: 'chanukah', group: 'שבת ומועדים', title: 'חנוכה',
    d: 'שמונה לילות של אור: הדלקה, הלל ו״על הניסים״.',
    stops: [
      { n: 'ner-chanukah', sec: 'בלילה' },
      { n: 'amidah', sec: 'בבוקר' },
      { n: 'al-hanisim', note: 'נוסף ב״מודים״.' },
      { n: 'hallel', note: 'הלל שלם כל שמונת הימים.' },
      { n: 'chanukah-shacharit', note: 'קריאת הנשיאים.' },
      { n: 'birkat-hamazon', sec: 'בסעודה' },
      { n: 'al-hanisim', note: 'נוסף גם בברכת המזון.' },
    ],
  },
  {
    id: 'purim', group: 'שבת ומועדים', title: 'פורים',
    d: 'מזכירת עמלק דרך הצום — אל המגילה, המשלוחים והסעודה.',
    stops: [
      { n: 'parashat-zachor', sec: 'שבת זכור' },
      { n: 'taanit-esther', sec: 'י״ג באדר' },
      { n: 'megilla', sec: 'ליל פורים' },
      { n: 'amidah', sec: 'יום פורים' },
      { n: 'al-hanisim' },
      { n: 'megilla', note: 'קריאה שנייה ביום.' },
      { n: 'purim-day' },
      { n: 'birkat-hamazon', note: 'סעודת פורים עם ״על הניסים״.' },
    ],
  },

  // ───────────────────────── אבל וזיכרון ─────────────────────────
  {
    id: 'tisha-bav', group: 'אבל וזיכרון', title: 'תשעה באב',
    d: 'יום האבל הלאומי על חורבן הבית: ישיבה על הארץ, מגילת איכה, קינות, וערב היום — ״נחם״.',
    stops: [
      { n: 'arvit-tisha', sec: 'ליל ט׳ באב' },
      { n: 'eicha' },
      { n: 'kinot', sec: 'בוקר', note: 'בלי טלית ותפילין בשחרית (לרוב המנהגים).' },
      { n: 'kriat-hatorah', note: '״כי תוליד בנים״ והפטרת ״אסוף אסיפם״.' },
      { n: 'amidah', sec: 'מנחה', note: 'בטלית ובתפילין.' },
      { n: 'nachem', note: 'נוסף ל״בונה ירושלים״.' },
      { n: 'aneinu' },
    ],
  },
  {
    id: 'avelut', group: 'אבל וזיכרון', title: 'אבלות ואזכרה',
    d: 'מן הקריעה והקבורה, דרך ימי השבעה, ועד הקדיש וההזכרות לאורך השנה. מסלול רגיש — ההסברים כאן כלליים, ומומלץ לשאול רב קהילה.',
    stops: [
      { n: 'kriah', sec: 'פטירה וקבורה' },
      { n: 'tziduk-hadin' },
      { n: 'maavar-yabbok', cond: 'optional', only: ['kabbalah', 'em', 'ash', 'sef'], note: 'למנהג חברות קדישא הנוהגות על פיו.' },
      { n: 'hashkava', cond: 'custom', only: ['em', 'kabbalah'] },
      { n: 'kaddish-yatom', note: 'הקדיש הראשון — ליד הקבר.' },
      { n: 'birkat-avelim', sec: 'השבעה', note: 'אחרי סעודת ההבראה ובכל ימי השבעה.' },
      { n: 'tachanun', cond: 'conditional', omit: true, note: 'בבית האבל אין אומרים תחנון.' },
      { n: 'kaddish-yatom', note: 'בכל תפילה בבית האבל.' },
      { n: 'mishnayot-avel', cond: 'custom' },
      { n: 'kaddish-yatom', sec: 'השנה הראשונה', note: 'כ־11 חודשים.' },
      { n: 'yizkor', sec: 'הזכרות', cond: 'custom', only: ['ash', 'sef'] },
      { n: 'hashkava', cond: 'custom', only: ['em', 'kabbalah'], note: 'ביום השנה ובעליות לתורה.' },
    ],
  },

  // ───────────────────────── סוד ─────────────────────────
  {
    id: 'kabbalah-night', group: 'סוד', title: 'לילה ובוקר של מקובלים',
    d: 'סדר היום כפי שעיצבו אותו מקובלי צפת: קריאת שמע שעל המיטה, קימה לתיקון חצות, לשם יחוד ופתח אליהו לפני התפילה.',
    stops: [
      { n: 'kriat-shema-al-hamita', sec: 'לפני השינה' },
      { n: 'ana-bekoach' },
      { n: 'tikkun-chatzot', sec: 'חצות הלילה', note: 'תיקון רחל ותיקון לאה.' },
      { n: 'leshem-yichud', sec: 'עם שחר' },
      { n: 'modeh-ani' },
      { n: 'birchot-hashachar' },
      { n: 'tallit' },
      { n: 'tefillin' },
      { n: 'petichat-eliyahu' },
      { n: 'akeda-korbanot' },
      KS.korbanot,
      { n: 'pesukei-dezimra', note: 'עולם היצירה — ״מברוך שאמר עד יוצר אור״ (שער הכוונות).' },
      KS.pesukei,
      { n: 'shema', sec: 'התפילה', note: 'כוונות קריאת שמע — ראו את קטע ״שער הכוונות״.' },
      { n: 'amidah' },
    ],
  },
];
