// Data loading with caching. All content lives in /data (generated by scripts/build-content.mjs).
const BASE = import.meta.env.BASE_URL + 'data/';
const cache = new Map();

async function getJSON(path) {
  if (!cache.has(path)) {
    const p = fetch(BASE + path).then((r) => {
      if (!r.ok) throw new Error(`HTTP ${r.status} — ${path}`);
      return r.json();
    });
    cache.set(path, p);
    p.catch(() => cache.delete(path));
  }
  return cache.get(path);
}

export const loadWorld = () => getJSON('world.json');
export const loadText = (id) => getJSON(`t/${id}.json`);
export const loadPreview = (nusach) => getJSON(`preview-${nusach}.json`);
export const loadSearch = (nusach) => getJSON(`search-${nusach}.json`);
