// Data loading with caching. All content lives in /data (generated by scripts/build-content.mjs).
import type { NusachId, SearchEntry, TextPayload, World } from './types';
import { foldFinals } from './hebrew';

const BASE = import.meta.env.BASE_URL + 'data/';
const cache = new Map<string, Promise<unknown>>();

function getJSON<T>(path: string): Promise<T> {
  if (!cache.has(path)) {
    const p = fetch(BASE + path).then((r) => {
      if (!r.ok) throw new Error(`HTTP ${r.status} — ${path}`);
      return r.json();
    });
    cache.set(path, p);
    p.catch(() => cache.delete(path));
  }
  return cache.get(path) as Promise<T>;
}

export async function loadWorld(): Promise<World> {
  const w = await getJSON<World>('world.json');
  w.nodeMap = new Map(w.nodes.map((n) => [n.id, n]));
  w.routeMap = new Map(w.routes.map((r) => [r.id, r]));
  w.regionMap = new Map(w.regions.map((r) => [r.id, r]));
  return w;
}

export const loadText = (id: string) => getJSON<TextPayload>(`t/${id}.json`);
export const loadPreview = (n: NusachId) => getJSON<Record<string, string>>(`preview-${n}.json`);

const searchCache = new Map<NusachId, Promise<SearchEntry[]>>();
/** Full-text index; `f` is a final-letter-folded copy of `x` (same length, positions align). */
export function loadSearch(n: NusachId): Promise<SearchEntry[]> {
  if (!searchCache.has(n)) {
    const p = getJSON<{ n: string; x: string }[]>(`search-${n}.json`).then((idx) => idx.map((e) => ({ ...e, f: foldFinals(e.x) })));
    searchCache.set(n, p);
    p.catch(() => searchCache.delete(n));
  }
  return searchCache.get(n)!;
}
