// Data loading with caching. All content lives in /data (generated by scripts/build-content.mjs).
const BASE = import.meta.env.BASE_URL + 'data/';
const cache = new Map();

async function getJSON(path) {
  if (!cache.has(path)) {
    const p = fetch(BASE + path).then((r) => {
      if (!r.ok) throw new Error(`HTTP ${r.status} — ${path}`);
      return r.json();
    });
    cache.set(path, p);
    p.catch(() => cache.delete(path));
  }
  return cache.get(path);
}

export const loadWorld = () => getJSON('world.json');
export const loadText = (id) => getJSON(`t/${id}.json`);
export const loadPreview = (nusach) => getJSON(`preview-${nusach}.json`);
const FINALS = { 'ך': 'כ', 'ם': 'מ', 'ן': 'נ', 'ף': 'פ', 'ץ': 'צ' };
const searchCache = new Map();
/** Search index; `f` is a final-letter-folded copy of `x` (same length, so positions align). */
export function loadSearch(nusach) {
  if (!searchCache.has(nusach)) {
    searchCache.set(nusach, getJSON(`search-${nusach}.json`).then((idx) => idx.map((e) => ({ ...e, f: e.x.replace(/[ךםןףץ]/g, (c) => FINALS[c]) }))));
    searchCache.get(nusach).catch(() => searchCache.delete(nusach));
  }
  return searchCache.get(nusach);
}
